Icon-based buttons to workaround scaling issue
hardpixel/unite-shell pull request #356
Opened 2023-11-27 20:34 UTC by ilya-m32

**Needs discussion, not for merging**

A workaround for https://github.com/hardpixel/unite-shell/issues/106

It seems that the problem still exist in gnome-shell=45.0 and there's no reaction from the gnome team.

Since the bug is very annoying to me, I decided to take a look if there are any fixes we can do now. I found that if we leverage gicons instead of CSS backgrounds, shell renders icon size correctly after the screen scale changes. It is less convenient than CSS-based styling but works as intended.

For testing purposes, I converted `adwaita` and `ambience` themes to gicons in backward-compatible fashion and personally satisfied with this workaround.

@jonian let me know what do you think. I can make a separate independent theme with this fix (for people like me with multi-scale setups) or try to convert other themes to gicons as well.

To all: extra testing could be also useful. I only tested this is gnome 45.0 with these two themes.

2023-12-18 21:40 UTC, ilya-m32 commented
@jonian wdyt if I convert the remaining themes?
​

2024-10-26 14:08 UTC, ilya-m32 commented
Hello @jonian 
As we discussed some time ago (https://github.com/hardpixel/unite-shell/issues/373#issuecomment-2323352557), I updated this PR to be optional and it can be enabled via extension settings. Let me know what do you think.

![Screenshot from 2024-10-26 16-04-56](https://github.com/user-attachments/assets/30bb60cd-a920-430f-830a-73919c34d2d6)

I tested it locally, but more testing is always welcomed.

2024-10-26 14:10 UTC, ilya-m32 commented on unite@hardpixel.eu/metadata.json
> +  "url": "https://github.com/ilya-m32/unite-shell",
I will revert this once we will be happy with parts of this PR

2024-10-27 07:50 UTC, jonian commented
Hey @ilya-m32, thanks for working on this! 

It looks mostly good and the only issue I found is that, if I disable the workaround setting, the icons do not revert to the default (css) mode if I don't also change the theme. 

Also I would avoid making some of the code changes in this PR and I will comment on them separately.

2024-10-27 07:59 UTC, jonian requested changes

2024-10-27 07:59 UTC, jonian commented on unite@hardpixel.eu/buttons.js
> +      this._actionIcons = params.actionIcons
Prefer using `setControlThemeParams` to set these since it is a workaround and might be removed in the future.

2024-10-27 07:59 UTC, jonian commented on unite@hardpixel.eu/buttons.js
> +      const btn = new St.Button({track_hover: true})
This change is not needed since it is the same with the original.

2024-10-27 07:59 UTC, jonian commented on unite@hardpixel.eu/panel.js
> +    })
Prefer using `setControlThemeParams` to set these since it is a workaround and might be removed in the future.

2024-10-27 07:59 UTC, jonian commented on unite@hardpixel.eu/panel.js
> +    this.theme = newTheme
Use a `const prevTheme` to avoid introducing changes to the existing code.

2024-10-27 12:41 UTC, ilya-m32 commented
@jonian thanks for the swift reaction - I applied suggested changes. I also added a callback on configuration change, so it will update the rendering mode without extension/shell restart.

I've noticed that the fix is not pixel perfect but it should be good enough for a temporary workaround in my opinion.

2024-10-27 14:03 UTC, jonian commented
@ilya-m32 looks great, thank you for your contribution!

2024-10-27 14:03 UTC, merged

2024-10-27 14:07 UTC, jonian commented
Fix #373 #106